### ISSUE TITLE
AVSRepoGUI code

### ISSUE THREAD

**Issue by camjac251** [theChaosCoder/VSRepoGUI#3]
I am unable to find the code for AVSRepoGUI. There's a compiled release but no source code.

Could the AVSRepoGUI code get its own repository?

**Comment by theChaosCoder** [comment]
VSRepo code = AVSRepo code. There is a switch for vs/avs. (could not figure out how to do it during compile time in visual studio)

avsrepogui was not really planned. I only added it because it was a no brainer since both apps are doing exactly the same, only with a different name and json file.

I could make a seperate repo. Maybe move vsrepo + gui to https://github.com/avisynth-repository ?

**Comment by camjac251** [comment]
I think having them be separate repositories allows the codebase to clearer to read.

**Comment by camjac251** [comment]
Or do you mean in this group but still be 2 separate repos.

**Comment by theChaosCoder** [comment]
ah yeah, I meant to move **a**vsrepo + avsrepogui

**Comment by theChaosCoder** [comment]
AVSRepoGUI has now its own repo https://github.com/theChaosCoder/AVSRepoGUI
